name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Create Properties File
      run: touch local.properties
    - name: Build Android App
      uses: sparkfabrik/android-build-action@v1.3.4

