name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.5
    - name: Create Properties File
      run: touch local.properties
    - name: Build Android App
      uses: sparkfabrik/android-build-action@v1.3.4
      with:
        project-path: android
        ruby-version: "2.7.5"
        bundler-version: "2.3.26"
        fastlane-env: "debug"
